Import-Module -Name ([System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName([System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)), "Util", "Test-AdministratorPrivileges.ps1")) -Global -Force
Import-Module -Name ([System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName([System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)), "Util", "Get-FastestMirror.ps1")) -Global -Force

function Get-CygwinMirror {
    
    # Getting mirror from system or user environment variable
    $mirror = if (Test-AdministratorPrivileges) {
        [System.Environment]::GetEnvironmentVariable("CygwinMirror", [System.EnvironmentVariableTarget]::Machine)
    } else {
        [System.Environment]::GetEnvironmentVariable("CygwinMirror", [System.EnvironmentVariableTarget]::User)
    }

    if ($null -eq $mirror) {

        $mirrors = [System.Collections.ArrayList]::new()
        [void]$mirrors.Add("http://ftp.is.co.za/mirrors/cygwin/")
        [void]$mirrors.Add("https://mirrors.163.com/cygwin/")
        [void]$mirrors.Add("https://mirrors.huaweicloud.com/cygwin/")
        [void]$mirrors.Add("https://mirrors.neusoft.edu.cn/cygwin/")
        [void]$mirrors.Add("https://mirrors.sjtug.sjtu.edu.cn/cygwin/")
        [void]$mirrors.Add("https://mirrors.tencent.com/cygwin/")
        [void]$mirrors.Add("https://mirrors.ustc.edu.cn/cygwin/")
        [void]$mirrors.Add("https://mirror-hk.koddos.net/cygwin/")
        [void]$mirrors.Add("rsync://mirror-hk.koddos.net/cygwin/")
        [void]$mirrors.Add("https://mirror.isoc.org.il/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.iij.ad.jp/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.iij.ad.jp/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.jaist.ac.jp/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.jaist.ac.jp/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.yz.yamagata-u.ac.jp/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.yz.yamagata-u.ac.jp/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.kaist.ac.kr/cygwin/")
        [void]$mirrors.Add("ftp://ftp.kaist.ac.kr/cygwin/")
        [void]$mirrors.Add("rsync://ftp.kaist.ac.kr/cygwin/")
        [void]$mirrors.Add("https://ftp.kr.freebsd.org/pub/cygwin.com/cygwin/")
        [void]$mirrors.Add("ftp://ftp.kr.freebsd.org/pub/cygwin.com/cygwin/")
        [void]$mirrors.Add("rsync://ftp.kr.freebsd.org/cygwin/cygwin/")
        [void]$mirrors.Add("http://mirror.rise.ph/cygwin/cygwin/")
        [void]$mirrors.Add("ftp://mirror.rise.ph/cygwin/cygwin/")
        [void]$mirrors.Add("https://download.nus.edu.sg/mirror/cygwin/")
        [void]$mirrors.Add("https://ftp.ntu.edu.tw/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.ntu.edu.tw/pub/cygwin/")
        [void]$mirrors.Add("http://ftp.twaren.net/Unix/sourceware.org/cygwin/")
        [void]$mirrors.Add("ftp://ftp.twaren.net/Unix/sourceware.org/cygwin/")
        [void]$mirrors.Add("https://mirror.aarnet.edu.au/pub/sourceware/cygwin/")
        [void]$mirrors.Add("http://mirror.internode.on.net/pub/cygwin/")
        [void]$mirrors.Add("ftp://mirror.internode.on.net/pub/cygwin/")
        [void]$mirrors.Add("https://mirror.lagoon.nc/cygwin/")
        [void]$mirrors.Add("ftp://mirror.lagoon.nc/cygwin/")
        [void]$mirrors.Add("rsync://mirror.lagoon.nc/cygwin/")
        [void]$mirrors.Add("http://ucmirror.canterbury.ac.nz/cygwin/")
        [void]$mirrors.Add("https://muug.ca/mirror/cygwin/")
        [void]$mirrors.Add("ftp://ftp.muug.ca/mirror/cygwin/")
        [void]$mirrors.Add("https://mirror.csclub.uwaterloo.ca/cygwin/")
        [void]$mirrors.Add("ftp://mirror.csclub.uwaterloo.ca/cygwin/")
        [void]$mirrors.Add("http://cygwin.mirror.rafal.ca/")
        [void]$mirrors.Add("ftp://cygwin.mirror.rafal.ca/pub/cygwin/")
        [void]$mirrors.Add("https://cygwin.mirror.globo.tech/")
        [void]$mirrors.Add("https://mirror.easyname.at/cygwin/")
        [void]$mirrors.Add("ftp://mirror.easyname.at/cygwin/")
        [void]$mirrors.Add("rsync://mirror.easyname.at/cygwin/")
        [void]$mirrors.Add("https://ftp.byfly.by/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.byfly.by/pub/cygwin/")
        [void]$mirrors.Add("rsync://ftp.byfly.by/cygwin/")
        [void]$mirrors.Add("https://mirror.datacenter.by/pub/mirrors/cygwin/")
        [void]$mirrors.Add("ftp://mirror.datacenter.by/pub/mirrors/cygwin/")
        [void]$mirrors.Add("rsync://mirror.datacenter.by/cygwin/")
        [void]$mirrors.Add("https://mirrors.netix.net/cygwin/")
        [void]$mirrors.Add("ftp://mirrors.netix.net/cygwin/")
        [void]$mirrors.Add("rsync://mirrors.netix.net/cygwin/")
        [void]$mirrors.Add("https://mirrors.dotsrc.org/cygwin/")
        [void]$mirrors.Add("ftp://mirrors.dotsrc.org/mirrors/cygwin/")
        [void]$mirrors.Add("https://cygwin.mbwarez.dk/")
        [void]$mirrors.Add("https://ftp.funet.fi/pub/mirrors/sourceware.org/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.funet.fi/pub/mirrors/sourceware.org/pub/cygwin/")
        [void]$mirrors.Add("https://mirrors.filigrane-technologie.fr/cygwin/")
        [void]$mirrors.Add("https://ftp.lip6.fr/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.lip6.fr/pub/cygwin/")
        [void]$mirrors.Add("rsync://ftp.lip6.fr/ftp/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.fau.de/cygwin/")
        [void]$mirrors.Add("ftp://ftp.fau.de/cygwin/")
        [void]$mirrors.Add("rsync://ftp.fau.de/cygwin/")
        [void]$mirrors.Add("https://ftp-stud.hs-esslingen.de/pub/Mirrors/sources.redhat.com/cygwin/")
        [void]$mirrors.Add("ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/sources.redhat.com/cygwin/")
        [void]$mirrors.Add("https://www.gutscheinrausch.de/mirror/cygwin/")
        [void]$mirrors.Add("https://ftp.halifax.rwth-aachen.de/cygwin/")
        [void]$mirrors.Add("ftp://ftp.halifax.rwth-aachen.de/cygwin/")
        [void]$mirrors.Add("rsync://ftp.halifax.rwth-aachen.de/cygwin/")
        [void]$mirrors.Add("https://ftp.inf.tu-dresden.de/software/windows/cygwin32/")
        [void]$mirrors.Add("ftp://ftp.inf.tu-dresden.de/software/windows/cygwin32/")
        [void]$mirrors.Add("rsync://ftp.inf.tu-dresden.de/cygwin/")
        [void]$mirrors.Add("https://cygwin.itefix.net/")
        [void]$mirrors.Add("https://linux.rz.ruhr-uni-bochum.de/download/cygwin/")
        [void]$mirrors.Add("ftp://linux.rz.ruhr-uni-bochum.de/cygwin/")
        [void]$mirrors.Add("https://mirror.checkdomain.de/cygwin/")
        [void]$mirrors.Add("ftp://mirror.checkdomain.de/cygwin/")
        [void]$mirrors.Add("https://mirror.clientvps.com/cygwin/")
        [void]$mirrors.Add("https://mirror.dogado.de/cygwin/")
        [void]$mirrors.Add("http://ftp.ntua.gr/pub/pc/cygwin/")
        [void]$mirrors.Add("ftp://ftp.ntua.gr/pub/pc/cygwin/")
        [void]$mirrors.Add("https://ftp.fsn.hu/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.fsn.hu/pub/cygwin/")
        [void]$mirrors.Add("https://sourceware.mirror.garr.it/cygwin/")
        [void]$mirrors.Add("https://mirror.mangohost.net/cygwin/")
        [void]$mirrors.Add("rsync://mirror.mangohost.net/cygwin/")
        [void]$mirrors.Add("https://mirror.koddos.net/cygwin/")
        [void]$mirrors.Add("rsync://mirror.koddos.net/cygwin/")
        [void]$mirrors.Add("https://ftp.snt.utwente.nl/pub/software/cygwin/")
        [void]$mirrors.Add("ftp://ftp.snt.utwente.nl/pub/software/cygwin/")
        [void]$mirrors.Add("rsync://ftp.snt.utwente.nl/cygwin-ftp/")
        [void]$mirrors.Add("https://cygwin.cathedral-networks.org/")
        [void]$mirrors.Add("https://mirror.terrahost.no/cygwin/")
        [void]$mirrors.Add("https://cygwin.uib.no/")
        [void]$mirrors.Add("https://cygwin.viem-it.no/")
        [void]$mirrors.Add("rsync://mirrors.viem-it.no/cygwin/")
        [void]$mirrors.Add("https://polish-mirror.evolution-host.com/cygwin/")
        [void]$mirrors.Add("https://sunsite.icm.edu.pl/pub/cygnus/cygwin/")
        [void]$mirrors.Add("ftp://sunsite.icm.edu.pl/pub/cygnus/cygwin/")
        [void]$mirrors.Add("https://ftp.eq.uc.pt/software/pc/prog/cygwin/")
        [void]$mirrors.Add("ftp://ftp.eq.uc.pt/pub/software/pc/prog/cygwin/")
        [void]$mirrors.Add("https://ftp.rnl.tecnico.ulisboa.pt/pub/cygwin/")
        [void]$mirrors.Add("ftp://ftp.rnl.tecnico.ulisboa.pt/pub/cygwin/")
        [void]$mirrors.Add("https://ftp.acc.umu.se/mirror/cygwin/")
        [void]$mirrors.Add("ftp://ftp.acc.umu.se/mirror/cygwin/")
        [void]$mirrors.Add("rsync://ftp.acc.umu.se/mirror/cygwin/")
        [void]$mirrors.Add("https://cygwin.mirror.uk.sargasso.net/")
        [void]$mirrors.Add("https://linorg.usp.br/cygwin/")
        [void]$mirrors.Add("https://mirrors.kernel.org/sourceware/cygwin/")
        [void]$mirrors.Add("https://mirrors.sonic.net/cygwin/")
        [void]$mirrors.Add("ftp://mirrors.sonic.net/cygwin/")
        [void]$mirrors.Add("http://mirrors.syringanetworks.net/cygwin/")
        [void]$mirrors.Add("ftp://mirrors.syringanetworks.net/cygwin/")
        [void]$mirrors.Add("rsync://mirrors.syringanetworks.net/cygwin/")
        [void]$mirrors.Add("https://mirror.steadfast.net/cygwin/")
        [void]$mirrors.Add("rsync://mirror.steadfast.net/cygwin/")
        [void]$mirrors.Add("http://mirror.team-cymru.com/cygwin/")
        [void]$mirrors.Add("rsync://mirror.team-cymru.com/cygwin/")
        [void]$mirrors.Add("https://cygwin.mirror.constant.com/")
        [void]$mirrors.Add("https://mirror.clarkson.edu/cygwin/")
        [void]$mirrors.Add("https://mirrors.rit.edu/cygwin/")
        [void]$mirrors.Add("https://cygwin.osuosl.org/")
        [void]$mirrors.Add("ftp://cygwin.osuosl.org/pub/cygwin/")
        [void]$mirrors.Add("rsync://rsync.osuosl.org/cygwin/")
        [void]$mirrors.Add("https://cygwin.mirrors.hoobly.com/")
        [void]$mirrors.Add("https://mirrors.xmission.com/cygwin/")
        [void]$mirrors.Add("ftp://mirrors.xmission.com/cygwin/")
        [void]$mirrors.Add("http://mirror.cs.vt.edu/pub/cygwin/cygwin/")
        [void]$mirrors.Add("ftp://mirror.cs.vt.edu/pub/cygwin/cygwin/")

        $mirror = Get-FastestMirror -MirrorList:$mirrors

        # Storing mirror on environment variable
        if (Test-AdministratorPrivileges) {
            [System.Environment]::SetEnvironmentVariable("CygwinMirror", $mirror, [System.EnvironmentVariableTarget]::Machine)
        }
        else {
            [System.Environment]::SetEnvironmentVariable("CygwinMirror", $mirror, [System.EnvironmentVariableTarget]::User)
        }

    }

    return $mirror
}